package com.nmp.studygeto.analytics

object TPAnalyticsConstants {
    const val Splash = "Splash" // 스플래시 화면 View
    const val Login = "Login" // 로그인 화면 View
    const val SignTrm = "SignTrm" // 회원가입 시 약관동의 화면 View
    const val SrvcTrm_btn = "SrvcTrm_btn" // 서비스 이용약관 전문 버튼 클릭 Click
    const val PrvcyTrm_btn = "PrvcyTrm_btn" // 개인정보수집 전문 버튼 클릭 Click
    const val IdtVrfct = "IdtVrfct" // 본인인증 화면 View
    const val InfoInp = "InfoInp" // 회원정보입력 화면 View
    const val SignDplct = "SignDplct" // 이미 가입된 회원 결과 화면 View
    const val SignLimit = "SignLimit" // 14세 미만 회원 가입 불가 화면 View
    const val SignDone = "SignDone" // 회원가입 완료 화면 View
    const val IdpwFind = "IdpwFind" // 아이디찾기/비밀번호 재설정 화면 View
    const val IdFind_btn = "IdFind_btn" // 아이디 찾기 버튼 클릭 Click
    const val IdFindCmplt = "IdFindCmplt" // 아이디 찾기 결과 화면(성공/실패) View
    const val PwResetTry_btn = "PwResetTry_btn" // 비밀번호 재설정 버튼 클릭 Click
    const val PwReset = "PwReset" // 비밀번호 재설정 화면(인증 완료) View
    const val Main = "Main" // 메인 화면 View
    const val MainMy_btn = "MainMy_btn" // 메인 화면 상단 My page 버튼 클릭 Click
    const val MainSrch_btn = "MainSrch_btn" // 메인 화면 상단 Search 버튼 클릭 Click
    const val MainStrnm_btn = "MainStrnm_btn" // 매장정보 내 매장명 클릭 Click
    const val Tckt_btn = "Tckt_btn" // 이용권 영역 클릭 Click
    const val MainTcktStrt_btn = "MainTcktStrt_btn" // 이용권 사용시작 버튼 클릭 Click
    const val SeatSlctn = "SeatSlctn" // 좌석 선택 화면 View
    const val TcktQR = "TcktQR" // 이용권 QR코드 출력 화면 View
    const val MainTcktEnd_btn = "MainTcktEnd_btn" // 이용권 퇴실 버튼 클릭 Click
    const val MainTcktExtns_btn = "MainTcktExtns_btn" // 이용권 기간(시간)연장 버튼 클릭 Click
    const val TcktExtnsSlctn = "TcktExtnsSlctn" // 이용권 기간(시간)연장 상품 선택 화면 View
    const val DtlsStrSrch_btn = "DtlsStrSrch_btn" // 매장 영역 내 매장찾기 버튼 클릭 Click
    const val DtlsStrTcktBuy_btn = "DtlsStrTcktBuy_btn" // 매장 영역 내 이용권 구매하기 버튼 클릭 Click
    const val My = "My" // 마이 페이지 화면 View
    const val MyNtc_btn = "MyNtc_btn" // 공지사항 버튼 클릭 Click
    const val MyNtf_btn = "MyNtf_btn" // 알림 버튼 클릭 Click
    const val MyFaq_btn = "MyFaq_btn" // 고객센터 버튼 클릭 Click
    const val MyPrchsHstry_btn = "MyPrchsHstry_btn" // 구매이력 버튼 클릭 Click
    const val MyStng_btn = "MyStng_btn" // 설정 버튼 클릭 Click
    const val MyQrlg_btn = "MyQrlg_btn" // 간편로그인 버튼 클릭 Click
    const val MyTckSlctn_btn = "MyTckSlctn_btn" // 이용권 선택 버튼 클릭 Click
    const val TckQrRflsh_btn = "TckQrRflsh_btn" // QR코드 다시보기 버튼 클릭 Click
    const val MyTckStrt_btn = "MyTckStrt_btn" // 이용권 사용시작 버튼 클릭 Click
    const val MyTckMvng_btn = "MyTckMvng_btn" // 이용권 자리이동 버튼 클릭 Click
    const val MyTckExtns_btn = "MyTckExtns_btn" // 이용권 시간(기간)연장 버튼 클릭 Click
    const val MyTckEnd_btn = "MyTckEnd_btn" // 이용권 퇴실 버튼 클릭 Click
    const val NtcList = "NtcList" // 공지사항 리스트 화면 View
    const val NtcDetail = "NtcDetail" // 공지사항 상세 화면 View
    const val NtfList = "NtfList" // 알림 리스트 화면 View
    const val FaqList = "FaqList" // 고객센터 리스트 화면 View
    const val FaqDetail = "FaqDetail" // 고객센터 FAQ 상세 화면 View
    const val FaqQstn_btn = "FaqQstn_btn" // 고객센터 1:1문의 접수 버튼 클릭 Click
    const val FaqQstnRgs_btn = "FaqQstnRgs_btn" // 고객센터 1:1문의 저장(등록) 버튼 클릭 Click
    const val FaqQstnDetail = "FaqQstnDetail" // 고객센터 1:1문의 상세 화면 View
    const val FaqQstnRe_btn = "FaqQstnRe_btn" // 고객센터 1:1문의 재문의 버튼 클릭 Click
    const val PrchsHstryList = "PrchsHstryList" // 구매이력 리스트 화면 View
    const val PrchsHstryDetail = "PrchsHstryDetail" // 구매이력 상세 화면 View
    const val PrchsHstryCncle = "PrchsHstryCncle" // 구매이력 결제취소 화면 View
    const val StngList = "StngList" // 설정 화면 View
    const val AccntInfoDetail = "AccntInfoDetail" // 내정보 화면 View
    const val AccntInfoPwReset_btn = "AccntInfoPwReset_btn" // 비밀번호 변경 버튼 클릭 Click
    const val AccntInfoPwRgs_btn = "AccntInfoPwRgs_btn" // 비밀번호 변경 저장 버튼 클릭 Click
    const val AccntInfoNmChng_btn = "AccntInfoNmChng_btn" // 이름 변경 버튼 클릭 Click
    const val AccntInfoPrtctnb_btn = "AccntInfoPrtctnb_btn" // 보호자번호 변경 버튼 클릭 Click
    const val StrSetList = "StrSetList" // 회원등록매장 관리 화면 View
    const val StrSetRemv_btn = "StrSetRemv_btn" // 회원등록해제 버튼 클릭 Click
    const val ApVsnUpdt_btn = "ApVsnUpdt_btn" // 앱버전 업데이트 버튼 클릭 Click
    const val Logout_btn = "Logout_btn" // 로그아웃 버튼 클릭 Click
    const val MmbrsWdrl = "MmbrsWdrl" // 회원탈퇴 화면 View
    const val SrvcTrm = "SrvcTrm" // 서비스 이용약관 전문 화면 View
    const val PrvcyTrm = "PrvcyTrm" // 개인정보 수집 약관 전문 화면 View
    const val MktTrm = "MktTrm" // 광고성 정보수신 동의 전문 화면 View
    const val LctnTrm = "LctnTrm" // 위치기반서비스 이용약관 전문 화면 View
    const val LcnsTrm = "LcnsTrm" // 라이선스 정보 화면 View
    const val StrFind = "StrFind" // 매장찾기 화면 View
    const val StrDetail = "StrDetail" // 매장별 상세 화면 View
    const val StrTck_btn = "StrTck_btn" // 보유중인 이용권 버튼 클릭 Click
    const val StrGoods_btn = "StrGoods_btn" // 매장 이용권 상품 버튼 클릭 Click
    const val StrRgs = "StrRgs" // 매장 회원 가입 화면 View
    const val StrPrtctTrm = "StrPrtctTrm" // 유료결제 부모동의 화면 View
    const val StrRoomSlctn = "StrRoomSlctn" // 이용권 구매 스터디룸 예약 화면 View
    const val StrLckrSlctn = "StrLckrSlctn" // 이용권 구매 사물함 배치도 화면 View
    const val StrInfo_btn = "StrInfo_btn" // 매장정보 탭 버튼 클릭 Click
    const val StrNtc_btn = "StrNtc_btn" // 공지사항 탭 버튼 클릭 Click
    const val StrNtcDetail = "StrNtcDetail" // 공지사항 상세 화면 View
    const val TckPymnt = "TckPymnt" // 이용권 결제 화면 View
    const val TckPymntDone = "TckPymntDone" // 이용권 결제 완료 화면 View
}